### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Wolly98** [eringee/BioData#4]
Hi, I have a question about the magic number 1023 in the code source: it is due to the fact that the dac have 10 bit? if my microcontroller have 16 bit I have to cange it ? 
The second question is if we have 5V we need to cange some variable in the code, it is corret?

**Comment by eringee** [comment]
Hi Wolly! Yes it is the 10bit ADC on Teensy/Arduino.  The Teensy ADC
functions in 3.3v but is 5v tolerant, so my circuits are sometimes built
around that. But the pulse sensor is 5v tolerant for example and everything
else should work fine with 5v as well.

Have fun!

E
